### PR TITLE
enforce `fn render` path invariants

### LINKED ISSUE #1958: fn render invariant: functions should not be able to modify resources outside of their current package
When running `kpt fn render`, a function in a package should only be able to modify and generate resources within the current package. If it tries to write outside of its package, kpt should fail with error.

i.e. fn-render/path-index-ancestor and fn-render/path-index-outofpkg should fail with exit code 1. 

cc @frankfarzan @droot @Shell32-Natsu 

ref: https://github.com/GoogleContainerTools/kpt/issues/1559

### PR DESCRIPTION
**Pull request by natasha41575**
close #1958 

This PR does 4 things: 

1. If a function in a pipeline tries to write to a file outside of its current package, `kpt fn render` will throw the error: 

`function must not modify resources outside of package: resource has path <filepath>`

2. Moves detection of path conflicts to the `fnruntime` package

3. Adds a test `generator-absolute-path` to show current behavior of a path beginning with `/` (it is treated as a relative path)  

4. Updates the test `path-index-current` to be run without a subpackage.

### CODE REVIEW

File: internal/cmdrender/executor.go [hunk 1]
```diff
@@ -425,6 +425,9 @@ func adjustRelPath(resources []*yaml.RNode, relPath string) ([]*yaml.RNode, erro
 				return resources, err
 			}
 		}
+		if strings.HasPrefix(path.Clean(currPath), "../") {
```
Comment (droot) [inline internal/cmdrender/executor.go:428]: couple of drive by comments:

shouldn't we do this check before updating the path annotation ? (above this code).

I am still noodling over another approach i.e. doing this in the `FunctionRunner` we have in pkg `fnruntime` instead of here. That's right after executing the function. I would like to enforce invariant as close as possible to the function execution.

is checking for `../` enough ?

File: e2e/testdata/fn-render/path-index-ancestor/.expected/config.yaml [hunk 2]
```diff
@@ -12,8 +12,5 @@
...
 # limitations under the License.
 
-# This package is nonIdempotent because functions in the subpackage (db)
-# do not have knowledge of the resources in the parent package. Therefore
-# when it runs twice, it tries to recreate the same resource in the parent,
-# resulting in a filepath conflict and throwing an error.
-nonIdempotent: true
\ No newline at end of file
+exitCode: 1
+stdErr: "Error: adjust relative path: cannot modify resources outside of package at path ../deployment_httpbin.yaml"
```
Comment (frankfarzan) [inline e2e/testdata/fn-render/path-index-ancestor/.expected/config.yaml:16]: "adjust relative path" seems out of palce

Comment (natasha41575) [reply e2e/testdata/fn-render/path-index-ancestor/.expected/config.yaml]: "adjust relative path" no longer shows up in the error message

File: internal/cmdrender/executor.go (hunk 1 above)
Comment (natasha41575) [reply internal/cmdrender/executor.go]: moved the logic to `fnruntime` package

also - I'm using path.Clean which should resolve things like `a/b/../../../c/d` to `../c/d`. Added a few unit tests for this.  Hopefully in this case checking for `../` is enough. I was trying to think of other ways that someone would be able to write outside of the package and none come to mind.

**Review by droot — CHANGES_REQUESTED** [review]

File: internal/fnruntime/runner.go [hunk 3]
```diff
@@ -208,6 +213,23 @@ func printFnExecErr(ctx context.Context, fnErr *ExecError) {
...
+// to a file outside the package
+func checkResourcePaths(resources []*yaml.RNode) error {
+	for _, r := range resources {
+		currPath, _, err := kioutil.GetFileAnnotations(r)
+		if err != nil {
+			return err
+		}
+		if strings.HasPrefix(path.Clean(currPath), "../") {
+			return fmt.Errorf("cannot modify resources outside of package: resource has path %s", currPath)
+		}
```
[the remark this answers is not in the document]
Comment (natasha41575) [reply internal/fnruntime/runner.go:228]: Both with and without a subpackage has the same output: 
```
Package "my-kpt-package": 
[RUNNING] "gcr.io/kpt-fn/starlark:unstable"
[FAIL] "gcr.io/kpt-fn/starlark:unstable"
Error: function must not modify resources outside of package: resource has path ../deployment_httpbin.yaml
```

[the remark this answers is not in the document]
Comment (natasha41575) [reply internal/fnruntime/runner.go:228]: Without subpkg: 

```
Package "my-kpt-package": 
[RUNNING] "gcr.io/kpt-fn/starlark:unstable"
[FAIL] "gcr.io/kpt-fn/starlark:unstable"
Error: function must not modify resources outside of package: resource has path ../deployment_httpbin.yaml
```

With subpkg:
```
Package "my-kpt-package/subpackage": 
Package "my-kpt-package": 
[RUNNING] "gcr.io/kpt-fn/starlark:unstable"
[FAIL] "gcr.io/kpt-fn/starlark:unstable"
Error: function must not modify resources outside of package: resource has path ../deployment_httpbin.yaml 
```

File: internal/fnruntime/runner.go [hunk 4]
```diff
@@ -208,6 +213,23 @@ func printFnExecErr(ctx context.Context, fnErr *ExecError) {
...
+// metadata.annotation field. checkResourcePaths ensures that those paths
+// only point to files within the package, throwing an error if there is a path
+// to a file outside the package
+func checkResourcePaths(resources []*yaml.RNode) error {
+	for _, r := range resources {
+		currPath, _, err := kioutil.GetFileAnnotations(r)
+		if err != nil {
+			return err
+		}
+		if strings.HasPrefix(path.Clean(currPath), "../") {
```
[the remark this answers is not in the document]
Comment (natasha41575) [reply internal/fnruntime/runner.go]: current behavior is "/directory" is treated the same as "./directory"

File: internal/fnruntime/runner.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (droot) [reply internal/fnruntime/runner.go:237]: ok. this is fine.

File: e2e/testdata/fn-render/path-index-ancestor/.expected/config.yaml [hunk 5]
```diff
@@ -12,8 +12,5 @@
...
 # limitations under the License.
 
-# This package is nonIdempotent because functions in the subpackage (db)
-# do not have knowledge of the resources in the parent package. Therefore
-# when it runs twice, it tries to recreate the same resource in the parent,
-# resulting in a filepath conflict and throwing an error.
-nonIdempotent: true
\ No newline at end of file
+exitCode: 1
+stdErr: "Error: function must not modify resources outside of package: resource has path ../deployment_httpbin.yaml"
```
Comment (droot) [inline e2e/testdata/fn-render/path-index-ancestor/.expected/config.yaml:16]: Can't believe that we managed to get the previous testcase merged.

File: internal/fnruntime/runner.go [hunk 6]
```diff
@@ -208,6 +213,33 @@ func printFnExecErr(ctx context.Context, fnErr *ExecError) {
 	pr.OptPrintf(printOpt.Stderr(), "  Exit code: %d\n\n", fnErr.ExitCode)
 }
 
+// path (location) of a KRM resources is tracked in a special key in
+// metadata.annotation field. checkResourcePaths throws an error if there is a path
+// to a file outside the package, or if the same index/path is on multiple resources
+func checkResourcePaths(nodes []*yaml.RNode) error {
```
Comment (droot) [inline internal/fnruntime/runner.go:219]: can we rename this function to `enforcePathInvariants`

File: internal/fnruntime/runner_test.go [hunk 7]
```diff
@@ -163,3 +167,317 @@ func TestMultilineFormatter(t *testing.T) {
...
+				if !assert.Error(t, err) {
+					t.FailNow()
+				}
+				assert.Equal(t, c.expectedErr, err.Error())
+			}
+		})
+	}
+}
+
+func TestDetectPathConflicts(t *testing.T) {
```
Comment (droot) [inline internal/fnruntime/runner_test.go:243]: You can probably combine these two test functions into `TestEnsurePathInvariants()`. They seem to be inconsistent right now (the implementation logic got merged, but these tests are still divergent :)

**Review by droot — CHANGES_REQUESTED** [review]
Looking good, some minor suggestions.

**Review by droot — APPROVED** [review]
Thanks for working on this. Really happy with the final result! 🚢  (ship it)
